spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/api?serverTimezone=UTC}
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:P4ssword!}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
        type:
          preferred_uuid_jdbc_type: CHAR
  docker:
    compose:
      lifecycle-management: start-only
error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
    codes:
      UserUidUnique: USER_UID_UNIQUE
      UserEmailUnique: USER_EMAIL_UNIQUE
      BookUidUnique: BOOK_UID_UNIQUE
      BookTitleUnique: BOOK_TITLE_UNIQUE
      ExchangeRequestUidUnique: EXCHANGE_REQUEST_UID_UNIQUE
      ExchangeRequestUserBookUnique: EXCHANGE_REQUEST_USER_BOOK_UNIQUE
      MessageUidUnique: MESSAGE_UID_UNIQUE
springdoc:
  pathsToMatch: /api/**
logging:
  level:
    root: WARN
    org:
      springframework:
        web: INFO
      hibernate: ERROR
    com:
      book_share:
        api: INFO
